version: '3.7'
services:

  calc-php-fpm:
    image: ${REGISTRY}/${PHP_FMP_CONTAINER_NAME}:${IMAGE_TAG}
    environment:
      MYSQL_HOST: '${MYSQL_HOST}'
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - .:/app

  calc-php-cli:
    image: ${REGISTRY}/${PHP_CLI_CONTAINER_NAME}:${IMAGE_TAG}
    environment:
      MYSQL_HOST: '${MYSQL_HOST}'
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - .:/app

  calc-nginx:
    image: ${REGISTRY}/${NGINX_CONTAINER_NAME}:${IMAGE_TAG}
    ports:
      - ${APP_WEB_PORT}:80
    volumes:
      - .:/app

  calc-mariadb:
    image: mariadb:10.3.34
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./docker/mariadb/initdb.d:/docker-entrypoint-initdb.d
      - /var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_general_ci']

  calc-redis:
    image: redis
    command: >
      --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./redis.conf:/urs/local/etc/redis/redis.conf
    ports:
      - '6379'

  calc-nodejs:
    image: node:16.13-alpine3.12
    volumes: 
      - .:/app
    command: npm run start:dev
    ports:
      - "3000:3000"
    working_dir: /app
